### PR TITLE
make seed data dates dynamic

### PR DESCRIPTION
**Pull request by robertjdominguez**
Change hardcoded seed data from what I assume was an export to use `NOW() - INTERVAL <interval>`.

NB: Duplicate of #5, but the branch name violated OCD's deploy syntax.

### CODE REVIEW

**Review by seanparkross — APPROVED** [review]
Works. 

cart_items dates are out of sync with carts, but, there's a lot of that ie: notifications dates with order dates. 

I don't think it's a big deal right now? Or we can fix it with relative dates across the board.

**Comment by robertjdominguez** [comment]
> I don't think it's a big deal right now? Or we can fix it with relative dates across the board.

For the sake of authenticity, you're right. However, the updates I made were targeted toward any recipes which are time-dependent. Didn't have the motivation on a Friday afternoon to modify all the extra lines of SQL in hopes of getting it perfect.

**Comment by seanparkross** [comment]
I'll add changes to this PR then yeah?

**Comment by robertjdominguez** [comment]
> I'll add changes to this PR then yeah?

I imagine this will take a bit of time with other work? If so, I'd rather this not be blocked. However, if you feel you can knock it out, tack them on and let me know. Happy to review before merging.

**Comment by seanparkross** [comment]
You can go ahead and merge and I will create another PR

**Pull request merged**
